repo: "fancy-hover-boxes"
canvasCourse: "web-design-2"

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - border-box
  - google-fonts

html:
  - path: "index.html"
    outline: false
    has:
      - [
          'link[href*="Asap+Condensed"]',
          "The Google Font, `Asap Condensed` (regular & bold) is missing",
        ]
    search:
      - "Orange butterflies"
      - "Black butterflies"
      - "Blue butterflies"
      - "Yellow butterflies"

css:
  - path: "css/main.css"
    has:
      - ["html", "font-family", '"Asap Condensed", sans-serif']
      - [".hover-box"]
      - [".hover-box img", ["filter", "transition"]]
      - [
          ".hover-box h2",
          ["bottom", "background-image", "text-shadow", "transition"],
        ]
    search:
      - "linear-gradient"
      - "linear"
      - ".2s"
      - "grayscale"
      - "transform"
      - "scale"

screenshots:
  - path: "index.html"
    sizes: [320, 680, 1440]

functionality:
  - path: "index.html"
    test: |
      const box = $('.hover-box:nth-child(3)');
      const capt = $('.hover-box:nth-child(3) h2');
      const img = $('.hover-box:nth-child(3) img');
      const oldCaptBot = css(capt).bottom;
      const oldImgTransform = css(img).transform;

      on(box, 'transitionend', () => {
        if (css(capt).bottom == oldCaptBot) return fail('The `bottom` coordinate of the `.hover-box h2` doesn’t change when hovered');
        if (css(img).transform == oldImgTransform) return fail('The `transform` property of the `.hover-box img` doesn’t change when hovered');
        pass();
      });

      hover(box);
